In [31]:
import torch

x = torch.ones(5)  # input tensor
y = torch.zeros(3)  # expected output
w = torch.randn(5, 3, requires_grad=True)
b = torch.randn(3, requires_grad=True)
z = torch.matmul(x, w)+b
z.retain_grad()
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)
loss.retain_grad()

In [32]:
print(f"Gradient function for z = {z.grad_fn}")
print(f"Gradient function for loss = {loss.grad_fn}")

Gradient function for z = <AddBackward0 object at 0x137dae0b0>
Gradient function for loss = <BinaryCrossEntropyWithLogitsBackward0 object at 0x127d14280>


In [33]:
loss.backward(retain_graph=True)
print(loss.grad)
print(z.grad)
print(w.grad)
print(b.grad)

tensor(1.)
tensor([0.1853, 0.2160, 0.3227])
tensor([[0.1853, 0.2160, 0.3227],
        [0.1853, 0.2160, 0.3227],
        [0.1853, 0.2160, 0.3227],
        [0.1853, 0.2160, 0.3227],
        [0.1853, 0.2160, 0.3227]])
tensor([0.1853, 0.2160, 0.3227])


In [19]:
z = torch.matmul(x, w)+b
print(z.requires_grad)

with torch.no_grad():
    z = torch.matmul(x, w)+b
print(z.requires_grad)

True
False


In [20]:
z = torch.matmul(x, w)+b
print(z.requires_grad)
z_det = z.detach()
print(z_det.requires_grad)

True
False
