In [115]:
import torch
print(torch.__version__)

2.5.1


In [116]:
a=[1.0, 2.0, 3.0]


In [117]:
a[0],a[2]

(1.0, 3.0)

In [118]:
a

[1.0, 2.0, 3.0]

In [119]:
import torch
a = torch.ones(3)
print(a)

tensor([1., 1., 1.])


In [120]:
a[1]

tensor(1.)

In [121]:
float(a[1])

1.0

In [122]:
a[2]=2.0
a

tensor([1., 1., 2.])

In [123]:
points = torch.zeros(6)
points[0]=4.0
points[1]=1.0
points[2]=5.0
points[3]=3.0
points[4]=2.0
points[5]=1.0
points

tensor([4., 1., 5., 3., 2., 1.])

In [124]:
#input via a python list
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [125]:
#first point index
float(points[0]), float(points[1])

(4.0, 1.0)

In [126]:
#2D points
points = torch.tensor([[4.0, 1.0],[5.0, 3.0],[2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [127]:
points.shape

torch.Size([3, 2])

In [128]:
points = torch.zeros(3,2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [129]:
points[0]=torch.tensor([4.0, 1.0])
points[1]=torch.tensor([5.0, 3.0])
points[2]=torch.tensor([2.0, 1.0])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [130]:
#single elem access
print(points[0][1])
print(points[0, 1])

tensor(1.)
tensor(1.)


In [131]:
#a single point
points[0]

tensor([4., 1.])

In [132]:
#range indexing
points[1:]

tensor([[5., 3.],
        [2., 1.]])

In [133]:
points[1:, :]

tensor([[5., 3.],
        [2., 1.]])

In [134]:
#first col
points[1:, 0]

tensor([5., 2.])

In [135]:
#Adds a dimension of size 1
points[None]

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

In [136]:
#ADD dtype to the tensor created
double_points = torch.ones(10,2, dtype=torch.double)
short_points = torch.tensor([[1,2], [3,4]], dtype=torch.short)

In [137]:
short_points.dtype

torch.int16

In [138]:
double_points.dtype

torch.float64

In [139]:
#casting operation
double_points = torch.zeros(10,2).double()
double_points.dtype

torch.float64

In [140]:
double_points = torch.zeros(10,2).to(torch.double)
double_points.dtype

torch.float64

In [141]:
points_64 = torch.rand(5, dtype=torch.double)
points_short = points_64.to(torch.short)
print(points_64)
print(points_short)

tensor([0.6494, 0.2034, 0.6505, 0.1920, 0.7270], dtype=torch.float64)
tensor([0, 0, 0, 0, 0], dtype=torch.int16)


In [142]:
points_64 * points_short


tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

In [143]:
#transpose
a= torch.ones(3,2)
a_t = torch.transpose(a, 0, 1)
a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [144]:
a_t=a.transpose(0,1)
a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [145]:
#tensor storage, elems in one after other.
points = torch.tensor([[4.0, 1.0],[5.0, 3.0],[2.0, 1.0]])
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [146]:
points_storage = points.storage()
points_storage[2]

5.0

In [147]:
points.storage()[1]

1.0

In [148]:
#stprage layout is 1D and changing it changes the tensor
points_storage[0]=8.0
points

tensor([[8., 1.],
        [5., 3.],
        [2., 1.]])

In [149]:
#inplace operations
a = torch.ones(3,2)
print("before:", a)
a.zero_()
a

before: tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [150]:
#view of tensor storage
second_point = points[1]
second_point.storage_offset()

2

In [151]:
second_point.size()

torch.Size([2])

In [152]:
second_point.shape

torch.Size([2])

In [153]:
#stride, num of elems to skip when index is +1 in each dimension
points.stride()

(2, 1)

In [154]:
second_point.stride()

(1,)

In [155]:
second_point

tensor([5., 3.])

In [156]:
#subtensor has the same storage and changing it will have side effect
second_point[0] = 9.0

In [157]:
points

tensor([[8., 1.],
        [9., 3.],
        [2., 1.]])

In [158]:
#subclone to avoid the side effect issue
points = torch.tensor([[4.0, 1.0],[5.0, 3.0],[2.0, 1.0]])
second_point = points[1].clone()
second_point[0] = 9.0
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [159]:
points_t = points.t()

In [160]:
id(points.storage()) == id(points_t.storage())

False

In [161]:
#id is the memory address of the object
id(points.storage())

4470304592

In [162]:
points.stride(), points_t.stride()

((2, 1), (1, 2))

In [163]:
#transpose in higher dimensions
some_t = torch.ones(3,4,5)
transpose_t = some_t.transpose(0,2)
some_t.shape, transpose_t.shape

(torch.Size([3, 4, 5]), torch.Size([5, 4, 3]))

In [164]:
some_t.stride(), transpose_t.stride()

((20, 5, 1), (1, 5, 20))

In [165]:
#contiguous tensors
points.is_contiguous()

True

In [166]:
points_t.is_contiguous()

False

In [167]:
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [168]:
points_t.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [169]:
points_t.stride()

(1, 2)

In [170]:
points_t_cont = points_t.contiguous()
points_t_cont

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [171]:
points_t_cont.storage()

 4.0
 5.0
 2.0
 1.0
 3.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [172]:
points_t_cont.stride()

(3, 1)

In [173]:
#for gpu work check the google colab notebook here
# https://colab.research.google.com/drive/1RhBmlT6806KX1yIONnCO-j1oxk1Ar7O-#scrollTo=DI_zo9XxhjKE


In [174]:
points = torch.ones(3,4)
points_np = points.numpy()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [175]:
points = torch.from_numpy(points_np)
points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [176]:
#serailaizing tensors and saving
#op 1
torch.save(points, '../data/p1ch3/ourpoints.t')

In [177]:
#op 2
with open('../data/p1ch3/ourpoints.t', 'wb') as f:
    torch.save(points, f)

In [178]:
#loading saved tensors
# op 1 
points = torch.load('../data/p1ch3/ourpoints.t')
points

/var/folders/vr/b837ndks0hd_73hq93kslgpc0000gp/T/ipykernel_8138/37628639.py:3: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  points = torch.load('../data/p1ch3/ourpoints.t')

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [179]:
# op 2
with open('../data/p1ch3/ourpoints.t', 'rb') as f:
    points = torch.load(f)
    
points

/var/folders/vr/b837ndks0hd_73hq93kslgpc0000gp/T/ipykernel_8138/3129085653.py:3: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  points = torch.load(f)


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [200]:
#Exercise 1
a = torch.tensor(range(9))
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [206]:
a.stride(), a.size(), a.storage_offset(), a.dtype

((1,), torch.Size([9]), 0, torch.int64)

In [202]:
b = a.view(3,3)
b, id(b.storage) == id(a.storage)

(tensor([[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]),
 True)

In [203]:
c = b[1:, 1:]
c.size(), c.stride(), c.storage_offset()

(torch.Size([2, 2]), (3, 1), 4)

In [207]:
d = torch.cos(a)
d

tensor([ 1.0000,  0.5403, -0.4161, -0.9900, -0.6536,  0.2837,  0.9602,  0.7539,
        -0.1455])

In [205]:
e = a.to(torch.float).cos_()
e, e.dtype

(tensor([ 1.0000,  0.5403, -0.4161, -0.9900, -0.6536,  0.2837,  0.9602,  0.7539,
         -0.1455]),
 torch.float32)